namespace PathCopyCopy.Settings.UI.UserControls
{
    partial class PluginPreviewUserControl
    {
        /// <summary> 
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary> 
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null)) {
                components.Dispose();
            }
            base.Dispose(disposing);

            // Code not generated by Component Designer
            settings?.Dispose();
            settings = null;
        }

        #region Component Designer generated code

        /// <summary> 
        /// Required method for Designer support - do not modify 
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            this.PreviewGroupBox = new System.Windows.Forms.GroupBox();
            this.PreviewTxt = new System.Windows.Forms.TextBox();
            this.PreviewGroupBox.SuspendLayout();
            this.SuspendLayout();
            // 
            // PreviewGroupBox
            // 
            this.PreviewGroupBox.Controls.Add(this.PreviewTxt);
            this.PreviewGroupBox.Dock = System.Windows.Forms.DockStyle.Fill;
            this.PreviewGroupBox.Location = new System.Drawing.Point(0, 0);
            this.PreviewGroupBox.Name = "PreviewGroupBox";
            this.PreviewGroupBox.Size = new System.Drawing.Size(369, 53);
            this.PreviewGroupBox.TabIndex = 0;
            this.PreviewGroupBox.TabStop = false;
            this.PreviewGroupBox.Text = "Preview";
            // 
            // PreviewTxt
            // 
            this.PreviewTxt.Anchor = ((System.Windows.Forms.AnchorStyles)(((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Left) 
            | System.Windows.Forms.AnchorStyles.Right)));
            this.PreviewTxt.Location = new System.Drawing.Point(6, 19);
            this.PreviewTxt.Name = "PreviewTxt";
            this.PreviewTxt.ReadOnly = true;
            this.PreviewTxt.Size = new System.Drawing.Size(357, 20);
            this.PreviewTxt.TabIndex = 0;
            // 
            // PluginPreviewUserControl
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 13F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.Controls.Add(this.PreviewGroupBox);
            this.Name = "PluginPreviewUserControl";
            this.Size = new System.Drawing.Size(369, 53);
            this.PreviewGroupBox.ResumeLayout(false);
            this.PreviewGroupBox.PerformLayout();
            this.ResumeLayout(false);

        }

        #endregion

        private System.Windows.Forms.GroupBox PreviewGroupBox;
        private System.Windows.Forms.TextBox PreviewTxt;
    }
}
