namespace PathCopyCopy.Settings.UI.UserControls
{
    partial class PluginPreviewUserControl
    {
        /// <summary> 
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary> 
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null)) {
                components.Dispose();
            }
            base.Dispose(disposing);

            // Code not generated by Component Designer
            settings?.Dispose();
            settings = null;
        }

        #region Component Designer generated code

        /// <summary> 
        /// Required method for Designer support - do not modify 
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(PluginPreviewUserControl));
            this.PreviewGroupBox = new System.Windows.Forms.GroupBox();
            this.PreviewTxt = new System.Windows.Forms.TextBox();
            this.PreviewGroupBox.SuspendLayout();
            this.SuspendLayout();
            // 
            // PreviewGroupBox
            // 
            resources.ApplyResources(this.PreviewGroupBox, "PreviewGroupBox");
            this.PreviewGroupBox.Controls.Add(this.PreviewTxt);
            this.PreviewGroupBox.Name = "PreviewGroupBox";
            this.PreviewGroupBox.TabStop = false;
            // 
            // PreviewTxt
            // 
            resources.ApplyResources(this.PreviewTxt, "PreviewTxt");
            this.PreviewTxt.Name = "PreviewTxt";
            this.PreviewTxt.ReadOnly = true;
            // 
            // PluginPreviewUserControl
            // 
            resources.ApplyResources(this, "$this");
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.Controls.Add(this.PreviewGroupBox);
            this.Name = "PluginPreviewUserControl";
            this.PreviewGroupBox.ResumeLayout(false);
            this.PreviewGroupBox.PerformLayout();
            this.ResumeLayout(false);

        }

        #endregion

        private System.Windows.Forms.GroupBox PreviewGroupBox;
        private System.Windows.Forms.TextBox PreviewTxt;
    }
}
