//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PathCopyCopy.Settings.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PathCopyCopy.Settings.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap BlankIcon {
            get {
                object obj = ResourceManager.GetObject("BlankIcon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PathCopyCopyCOMPluginExecutor32.exe.
        /// </summary>
        internal static string COM_PLUGIN_EXECUTOR_EXE_NAME_32 {
            get {
                return ResourceManager.GetString("COM_PLUGIN_EXECUTOR_EXE_NAME_32", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PathCopyCopyCOMPluginExecutor64.exe.
        /// </summary>
        internal static string COM_PLUGIN_EXECUTOR_EXE_NAME_64 {
            get {
                return ResourceManager.GetString("COM_PLUGIN_EXECUTOR_EXE_NAME_64", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Output: .
        /// </summary>
        internal static string COM_PLUGIN_EXECUTOR_OUTPUT_PREFIX {
            get {
                return ResourceManager.GetString("COM_PLUGIN_EXECUTOR_OUTPUT_PREFIX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy Cygwin Path.
        /// </summary>
        internal static string CYGWIN_PATH_PLUGIN_DESCRIPTION {
            get {
                return ResourceManager.GetString("CYGWIN_PATH_PLUGIN_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {CD50DCE3-9A5C-4adf-B552-1741361567D6}.
        /// </summary>
        internal static string CYGWIN_PATH_PLUGIN_ID {
            get {
                return ResourceManager.GetString("CYGWIN_PATH_PLUGIN_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap DefaultIcon {
            get {
                object obj = ResourceManager.GetObject("DefaultIcon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This function has been disabled by the administrator..
        /// </summary>
        internal static string EDITING_DISABLED_MESSAGE {
            get {
                return ResourceManager.GetString("EDITING_DISABLED_MESSAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editing disabled.
        /// </summary>
        internal static string EDITING_DISABLED_TITLE {
            get {
                return ResourceManager.GetString("EDITING_DISABLED_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grayed out custom commands cannot be selected because they would overwrite those configured by your system administrator..
        /// </summary>
        internal static string ImportPipelinePluginsForm_CantOverwriteGlobalMsg {
            get {
                return ResourceManager.GetString("ImportPipelinePluginsForm_CantOverwriteGlobalMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom commands with a listed version requirement are incompatible with this version of Path Copy Copy. They can still be imported, but they will be disabled..
        /// </summary>
        internal static string ImportPipelinePluginsForm_IncompatiblePluginsMsg {
            get {
                return ResourceManager.GetString("ImportPipelinePluginsForm_IncompatiblePluginsMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom Commands.
        /// </summary>
        internal static string ImportPipelinePluginsForm_MsgTitle {
            get {
                return ResourceManager.GetString("ImportPipelinePluginsForm_MsgTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy Internet Path.
        /// </summary>
        internal static string INTERNET_PATH_PLUGIN_DESCRIPTION {
            get {
                return ResourceManager.GetString("INTERNET_PATH_PLUGIN_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {8F2ADCCC-9693-407d-9300-FCCB9A12B982}.
        /// </summary>
        internal static string INTERNET_PATH_PLUGIN_ID {
            get {
                return ResourceManager.GetString("INTERNET_PATH_PLUGIN_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy Long Parent Folder Path.
        /// </summary>
        internal static string LONG_FOLDER_PLUGIN_DESCRIPTION {
            get {
                return ResourceManager.GetString("LONG_FOLDER_PLUGIN_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {349939D7-780F-43fd-A98E-83D9ADD44E22}.
        /// </summary>
        internal static string LONG_FOLDER_PLUGIN_ID {
            get {
                return ResourceManager.GetString("LONG_FOLDER_PLUGIN_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy Long Name.
        /// </summary>
        internal static string LONG_NAME_PLUGIN_DESCRIPTION {
            get {
                return ResourceManager.GetString("LONG_NAME_PLUGIN_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {3A42B5C6-72D6-4a8a-BA44-014FA64AA11A}.
        /// </summary>
        internal static string LONG_NAME_PLUGIN_ID {
            get {
                return ResourceManager.GetString("LONG_NAME_PLUGIN_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy Long Path.
        /// </summary>
        internal static string LONG_PATH_PLUGIN_DESCRIPTION {
            get {
                return ResourceManager.GetString("LONG_PATH_PLUGIN_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {331A3B60-AF49-44f4-B30D-56ADFF6D25E8}.
        /// </summary>
        internal static string LONG_PATH_PLUGIN_ID {
            get {
                return ResourceManager.GetString("LONG_PATH_PLUGIN_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy Long UNC Parent Folder Path.
        /// </summary>
        internal static string LONG_UNC_FOLDER_PATH_PLUGIN_DESCRIPTION {
            get {
                return ResourceManager.GetString("LONG_UNC_FOLDER_PATH_PLUGIN_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {E2C942AC-917C-4aee-A867-8F6AB960BA76}.
        /// </summary>
        internal static string LONG_UNC_FOLDER_PATH_PLUGIN_ID {
            get {
                return ResourceManager.GetString("LONG_UNC_FOLDER_PATH_PLUGIN_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy Long UNC Path.
        /// </summary>
        internal static string LONG_UNC_PATH_PLUGIN_DESCRIPTION {
            get {
                return ResourceManager.GetString("LONG_UNC_PATH_PLUGIN_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {EA24BCC3-35F5-46b9-A2A5-A12A0AED2D28}.
        /// </summary>
        internal static string LONG_UNC_PATH_PLUGIN_ID {
            get {
                return ResourceManager.GetString("LONG_UNC_PATH_PLUGIN_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://www.paypal.com/cgi-bin/webscr?cmd=_donations&amp;business=LM5B9WNTH4KN4&amp;lc=CA&amp;item_name=Charles%20Lechasseur&amp;item_number=PathCopyCopy&amp;currency_code=CAD&amp;bn=PP%2dDonationsBF%3abtn_donateCC_LG%2egif%3aNonHosted.
        /// </summary>
        internal static string MainForm_About_DonationsPageURI {
            get {
                return ResourceManager.GetString("MainForm_About_DonationsPageURI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://github.com/clechasseur/pathcopycopy/blob/master/LICENSE.
        /// </summary>
        internal static string MainForm_About_LicensePageURI {
            get {
                return ResourceManager.GetString("MainForm_About_LicensePageURI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        internal static string MainForm_Confirm_EditMsgTitle {
            get {
                return ResourceManager.GetString("MainForm_Confirm_EditMsgTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export Settings.
        /// </summary>
        internal static string MainForm_Confirm_ExportUserSettingsMsgTitle {
            get {
                return ResourceManager.GetString("MainForm_Confirm_ExportUserSettingsMsgTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In order to export settings, changes have to be applied first. Do you want to apply changes now?.
        /// </summary>
        internal static string MainForm_Confirm_ExportUserSettingsSaving {
            get {
                return ResourceManager.GetString("MainForm_Confirm_ExportUserSettingsSaving", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import.
        /// </summary>
        internal static string MainForm_Confirm_ImportMsgTitle {
            get {
                return ResourceManager.GetString("MainForm_Confirm_ImportMsgTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Some custom commands to be imported will overwrite existing ones. Do you want to import them anyway?.
        /// </summary>
        internal static string MainForm_Confirm_ImportPipelinePluginOverwrite {
            get {
                return ResourceManager.GetString("MainForm_Confirm_ImportPipelinePluginOverwrite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occured while trying to import the custom commands. The file appears to be corrupted..
        /// </summary>
        internal static string MainForm_Error_ImportPipelinePluginBadXMLFormat {
            get {
                return ResourceManager.GetString("MainForm_Error_ImportPipelinePluginBadXMLFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occured while trying to import the custom commands. The file appears to be empty..
        /// </summary>
        internal static string MainForm_Error_ImportPipelinePluginEmptyXML {
            get {
                return ResourceManager.GetString("MainForm_Error_ImportPipelinePluginEmptyXML", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occured while trying to interpret the data of this custom command. Perhaps it has been created by a newer version of Path Copy Copy? It will be impossible to edit it..
        /// </summary>
        internal static string MainForm_Error_InvalidPipelinePluginEncodedElements {
            get {
                return ResourceManager.GetString("MainForm_Error_InvalidPipelinePluginEncodedElements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings have been exported to &quot;{0}&quot;. To import them back (possibly on another machine), simply double-click the .reg file in Windows Explorer..
        /// </summary>
        internal static string MainForm_Msg_UserSettingsExported {
            get {
                return ResourceManager.GetString("MainForm_Msg_UserSettingsExported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings Exported.
        /// </summary>
        internal static string MainForm_Msg_UserSettingsExportedMsgTitle {
            get {
                return ResourceManager.GetString("MainForm_Msg_UserSettingsExportedMsgTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occured while exporting settings to &quot;{0}&quot;. Settings have not been successfully exported. (Exit code: {1}).
        /// </summary>
        internal static string MainForm_Msg_UserSettingsNotExported {
            get {
                return ResourceManager.GetString("MainForm_Msg_UserSettingsNotExported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings Not Exported.
        /// </summary>
        internal static string MainForm_Msg_UserSettingsNotExportedMsgTitle {
            get {
                return ResourceManager.GetString("MainForm_Msg_UserSettingsNotExportedMsgTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  (Copy).
        /// </summary>
        internal static string MainForm_PluginsDataGrid_DuplicateSuffix {
            get {
                return ResourceManager.GetString("MainForm_PluginsDataGrid_DuplicateSuffix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click to choose an icon file for this command.
        ///Shift-click to have this command use the default icon.
        ///Control-click to avoid displaying an icon for this command..
        /// </summary>
        internal static string MainForm_PluginsDataGrid_IconToolTipText {
            get {
                return ResourceManager.GetString("MainForm_PluginsDataGrid_IconToolTipText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy MSYS/MSYS2 Path.
        /// </summary>
        internal static string MSYS_PATH_PLUGIN_DESCRIPTION {
            get {
                return ResourceManager.GetString("MSYS_PATH_PLUGIN_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {31022A3D-6FEE-4B36-843E-BBB4556AB35B}.
        /// </summary>
        internal static string MSYS_PATH_PLUGIN_ID {
            get {
                return ResourceManager.GetString("MSYS_PATH_PLUGIN_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PCC32.dll.
        /// </summary>
        internal static string PCC_EXECUTOR_DLL_NAME_32 {
            get {
                return ResourceManager.GetString("PCC_EXECUTOR_DLL_NAME_32", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PCC64.dll.
        /// </summary>
        internal static string PCC_EXECUTOR_DLL_NAME_64 {
            get {
                return ResourceManager.GetString("PCC_EXECUTOR_DLL_NAME_64", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PathCopyCopy.dll.
        /// </summary>
        internal static string PCC_EXECUTOR_DLL_NAME_DEV {
            get {
                return ResourceManager.GetString("PCC_EXECUTOR_DLL_NAME_DEV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use Base Command.
        /// </summary>
        internal static string PipelineElement_ApplyPipelinePlugin {
            get {
                return ResourceManager.GetString("PipelineElement_ApplyPipelinePlugin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose a base command to use to get an initial path value.
        /// </summary>
        internal static string PipelineElement_ApplyPipelinePlugin_HelpText {
            get {
                return ResourceManager.GetString("PipelineElement_ApplyPipelinePlugin_HelpText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use Base Command (No Custom Command).
        /// </summary>
        internal static string PipelineElement_ApplyPlugin {
            get {
                return ResourceManager.GetString("PipelineElement_ApplyPlugin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose a base command (but not a custom command) to use to get an initial path value.
        /// </summary>
        internal static string PipelineElement_ApplyPlugin_HelpText {
            get {
                return ResourceManager.GetString("PipelineElement_ApplyPlugin_HelpText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Turn Backslashes Into Forward Slashes.
        /// </summary>
        internal static string PipelineElement_BackToForwardSlashes {
            get {
                return ResourceManager.GetString("PipelineElement_BackToForwardSlashes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Replace every backslash ( \ ) in the path with a forward slash ( / ).
        /// </summary>
        internal static string PipelineElement_BackToForwardSlashes_HelpText {
            get {
                return ResourceManager.GetString("PipelineElement_BackToForwardSlashes_HelpText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Email Links.
        /// </summary>
        internal static string PipelineElement_EmailLinks {
            get {
                return ResourceManager.GetString("PipelineElement_EmailLinks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Surround the path with &lt; and &gt; characters to create e-mail links.
        /// </summary>
        internal static string PipelineElement_EmailLinks_HelpText {
            get {
                return ResourceManager.GetString("PipelineElement_EmailLinks_HelpText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Encode URI Characters.
        /// </summary>
        internal static string PipelineElement_EncodeURIChars {
            get {
                return ResourceManager.GetString("PipelineElement_EncodeURIChars", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Replace all characters in the path that are invalid in a URI by percent-encoding ( %xx ).
        /// </summary>
        internal static string PipelineElement_EncodeURIChars_HelpText {
            get {
                return ResourceManager.GetString("PipelineElement_EncodeURIChars_HelpText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Encode URI Whitespace.
        /// </summary>
        internal static string PipelineElement_EncodeURIWhitespace {
            get {
                return ResourceManager.GetString("PipelineElement_EncodeURIWhitespace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Replace all whitespace characters in the path with %20.
        /// </summary>
        internal static string PipelineElement_EncodeURIWhitespace_HelpText {
            get {
                return ResourceManager.GetString("PipelineElement_EncodeURIWhitespace_HelpText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Option: Launch Executable.
        /// </summary>
        internal static string PipelineElement_Executable {
            get {
                return ResourceManager.GetString("PipelineElement_Executable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Instead of copying paths to the clipboard, launch an executable on disk, passing the paths as arguments.
        /// </summary>
        internal static string PipelineElement_Executable_HelpText {
            get {
                return ResourceManager.GetString("PipelineElement_Executable_HelpText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Option: Launch Executable With Filelist.
        /// </summary>
        internal static string PipelineElement_ExecutableWithFilelist {
            get {
                return ResourceManager.GetString("PipelineElement_ExecutableWithFilelist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Instead of copying paths to the clipboard, save them to a filelist, then launch an executable on disk, passing the filelist as argument.
        /// </summary>
        internal static string PipelineElement_ExecutableWithFilelist_HelpText {
            get {
                return ResourceManager.GetString("PipelineElement_ExecutableWithFilelist_HelpText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find / Replace.
        /// </summary>
        internal static string PipelineElement_FindReplace {
            get {
                return ResourceManager.GetString("PipelineElement_FindReplace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Replace every instance of a specific character string in the path with another.
        /// </summary>
        internal static string PipelineElement_FindReplace_HelpText {
            get {
                return ResourceManager.GetString("PipelineElement_FindReplace_HelpText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Follow Symbolic Link.
        /// </summary>
        internal static string PipelineElement_FollowSymlink {
            get {
                return ResourceManager.GetString("PipelineElement_FollowSymlink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Replace the path to a symbolic link with the path to its target.
        /// </summary>
        internal static string PipelineElement_FollowSymlink_HelpText {
            get {
                return ResourceManager.GetString("PipelineElement_FollowSymlink_HelpText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Turn Forward Slashes Into Backslashes.
        /// </summary>
        internal static string PipelineElement_ForwardToBackslashes {
            get {
                return ResourceManager.GetString("PipelineElement_ForwardToBackslashes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Replace every forward slash ( / ) in the path with a backslash ( \ ).
        /// </summary>
        internal static string PipelineElement_ForwardToBackslashes_HelpText {
            get {
                return ResourceManager.GetString("PipelineElement_ForwardToBackslashes_HelpText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Quotes If Needed.
        /// </summary>
        internal static string PipelineElement_OptionalQuotes {
            get {
                return ResourceManager.GetString("PipelineElement_OptionalQuotes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Surround the path with quotes ( &quot; ) if it contains spaces.
        /// </summary>
        internal static string PipelineElement_OptionalQuotes_HelpText {
            get {
                return ResourceManager.GetString("PipelineElement_OptionalQuotes_HelpText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Option: Paths Separator.
        /// </summary>
        internal static string PipelineElement_PathsSeparator {
            get {
                return ResourceManager.GetString("PipelineElement_PathsSeparator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configure the character string to use to separate multiple copied paths; if not present, a newline is used.
        /// </summary>
        internal static string PipelineElement_PathsSeparator_HelpText {
            get {
                return ResourceManager.GetString("PipelineElement_PathsSeparator_HelpText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Quotes.
        /// </summary>
        internal static string PipelineElement_Quotes {
            get {
                return ResourceManager.GetString("PipelineElement_Quotes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Surround the path with quotes ( &quot; ).
        /// </summary>
        internal static string PipelineElement_Quotes_HelpText {
            get {
                return ResourceManager.GetString("PipelineElement_Quotes_HelpText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find / Replace Using Regular Expressions.
        /// </summary>
        internal static string PipelineElement_Regex {
            get {
                return ResourceManager.GetString("PipelineElement_Regex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Perform a find/replace operation on the path using regular expressions.
        /// </summary>
        internal static string PipelineElement_Regex_HelpText {
            get {
                return ResourceManager.GetString("PipelineElement_Regex_HelpText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove File Extension.
        /// </summary>
        internal static string PipelineElement_RemoveExt {
            get {
                return ResourceManager.GetString("PipelineElement_RemoveExt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove any extension from the file at the end of the path.
        /// </summary>
        internal static string PipelineElement_RemoveExt_HelpText {
            get {
                return ResourceManager.GetString("PipelineElement_RemoveExt_HelpText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unexpand Environment Strings.
        /// </summary>
        internal static string PipelineElement_UnexpandEnvStrings {
            get {
                return ResourceManager.GetString("PipelineElement_UnexpandEnvStrings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Replaces parts of the path with environment variable references, if possible (like %USERPROFILE%, etc.).
        /// </summary>
        internal static string PipelineElement_UnexpandEnvStrings_HelpText {
            get {
                return ResourceManager.GetString("PipelineElement_UnexpandEnvStrings_HelpText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a name for the custom command..
        /// </summary>
        internal static string PipelinePluginForm_EmptyName {
            get {
                return ResourceManager.GetString("PipelinePluginForm_EmptyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom Command.
        /// </summary>
        internal static string PipelinePluginForm_MsgTitle {
            get {
                return ResourceManager.GetString("PipelinePluginForm_MsgTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This custom command is now too complex to be edited in Simple Mode. If you switch, you will lose some customization. Do you really want to switch to Simple Mode?.
        /// </summary>
        internal static string PipelinePluginForm_PipelineTooComplexForSimpleMode {
            get {
                return ResourceManager.GetString("PipelinePluginForm_PipelineTooComplexForSimpleMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} (Required version: {1}).
        /// </summary>
        internal static string PipelinePluginInfo_DescriptionWithRequiredVersion {
            get {
                return ResourceManager.GetString("PipelinePluginInfo_DescriptionWithRequiredVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #ERROR#.
        /// </summary>
        internal static string Plugin_PreviewError {
            get {
                return ResourceManager.GetString("Plugin_PreviewError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PathCopyCopyRegexTester.exe.
        /// </summary>
        internal static string REGEX_TESTER_EXE_NAME {
            get {
                return ResourceManager.GetString("REGEX_TESTER_EXE_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modified string: .
        /// </summary>
        internal static string REGEX_TESTER_MODIFIED_STRING_PREFIX {
            get {
                return ResourceManager.GetString("REGEX_TESTER_MODIFIED_STRING_PREFIX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to remove the &quot;{0}&quot; command?.
        /// </summary>
        internal static string REMOVE_PIPELINE_PLUGIN_MESSAGE {
            get {
                return ResourceManager.GetString("REMOVE_PIPELINE_PLUGIN_MESSAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove Custom Command.
        /// </summary>
        internal static string REMOVE_PIPELINE_PLUGIN_TITLE {
            get {
                return ResourceManager.GetString("REMOVE_PIPELINE_PLUGIN_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy Samba Path.
        /// </summary>
        internal static string SAMBA_PATH_PLUGIN_DESCRIPTION {
            get {
                return ResourceManager.GetString("SAMBA_PATH_PLUGIN_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {7DA6A4A2-AE54-40E0-9910-EBD9EF3F017E}.
        /// </summary>
        internal static string SAMBA_PATH_PLUGIN_ID {
            get {
                return ResourceManager.GetString("SAMBA_PATH_PLUGIN_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy Short Parent Folder Path.
        /// </summary>
        internal static string SHORT_FOLDER_PLUGIN_DESCRIPTION {
            get {
                return ResourceManager.GetString("SHORT_FOLDER_PLUGIN_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0929538B-5F52-4480-9902-2BBEC9C84905}.
        /// </summary>
        internal static string SHORT_FOLDER_PLUGIN_ID {
            get {
                return ResourceManager.GetString("SHORT_FOLDER_PLUGIN_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy Short Name.
        /// </summary>
        internal static string SHORT_NAME_PLUGIN_DESCRIPTION {
            get {
                return ResourceManager.GetString("SHORT_NAME_PLUGIN_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {C8757DCA-1BA8-48d0-8145-B93BBB9237AF}.
        /// </summary>
        internal static string SHORT_NAME_PLUGIN_ID {
            get {
                return ResourceManager.GetString("SHORT_NAME_PLUGIN_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy Short Path.
        /// </summary>
        internal static string SHORT_PATH_PLUGIN_DESCRIPTION {
            get {
                return ResourceManager.GetString("SHORT_PATH_PLUGIN_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {93B362D1-2B13-467a-B618-6784F24F3BA1}.
        /// </summary>
        internal static string SHORT_PATH_PLUGIN_ID {
            get {
                return ResourceManager.GetString("SHORT_PATH_PLUGIN_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy Short UNC Parent Folder Path.
        /// </summary>
        internal static string SHORT_UNC_FOLDER_PATH_PLUGIN_DESCRIPTION {
            get {
                return ResourceManager.GetString("SHORT_UNC_FOLDER_PATH_PLUGIN_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {73188FB3-8E14-409c-95EF-BA608FDC1274}.
        /// </summary>
        internal static string SHORT_UNC_FOLDER_PATH_PLUGIN_ID {
            get {
                return ResourceManager.GetString("SHORT_UNC_FOLDER_PATH_PLUGIN_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy Short UNC Path.
        /// </summary>
        internal static string SHORT_UNC_PATH_PLUGIN_DESCRIPTION {
            get {
                return ResourceManager.GetString("SHORT_UNC_PATH_PLUGIN_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {891F9E3E-0B70-49fd-A86C-53B21C6193C7}.
        /// </summary>
        internal static string SHORT_UNC_PATH_PLUGIN_ID {
            get {
                return ResourceManager.GetString("SHORT_UNC_PATH_PLUGIN_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy Unix Path.
        /// </summary>
        internal static string UNIX_PATH_PLUGIN_DESCRIPTION {
            get {
                return ResourceManager.GetString("UNIX_PATH_PLUGIN_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {5B5DA5CB-3284-45a9-A1E5-4D6B03107924}.
        /// </summary>
        internal static string UNIX_PATH_PLUGIN_ID {
            get {
                return ResourceManager.GetString("UNIX_PATH_PLUGIN_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://raw.githubusercontent.com/clechasseur/pcc-updates/master/UpdateInfo2.xml.
        /// </summary>
        internal static string UserSettings_DefaultUpdateChannel {
            get {
                return ResourceManager.GetString("UserSettings_DefaultUpdateChannel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://github.com/clechasseur/pathcopycopy/wiki/Custom-Commands.
        /// </summary>
        internal static string WikiLink_CustomCommands {
            get {
                return ResourceManager.GetString("WikiLink_CustomCommands", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://github.com/clechasseur/pathcopycopy/wiki/Custom-Commands-:-Expert-Mode.
        /// </summary>
        internal static string WikiLink_CustomCommandsExpertMode {
            get {
                return ResourceManager.GetString("WikiLink_CustomCommandsExpertMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://github.com/clechasseur/pathcopycopy/wiki/Settings.
        /// </summary>
        internal static string WikiLink_Settings {
            get {
                return ResourceManager.GetString("WikiLink_Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy WSL Path.
        /// </summary>
        internal static string WSL_PATH_PLUGIN_DESCRIPTION {
            get {
                return ResourceManager.GetString("WSL_PATH_PLUGIN_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {BD574871-5DF9-4B64-83D1-2AF9C0C17F66}.
        /// </summary>
        internal static string WSL_PATH_PLUGIN_ID {
            get {
                return ResourceManager.GetString("WSL_PATH_PLUGIN_ID", resourceCulture);
            }
        }
    }
}
