//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by PathCopyCopy.rc
//
#define IDS_PROJNAME                    100
#define IDR_PATHCOPYCOPY                101
#define IDS_PATH_COPY_MENU_ITEM         101
#define IDS_PATH_COPY_HINT              102
#define IDS_SAMPLE_PLUGIN_DESCRIPTION   103
#define IDS_SAMPLE_PLUGIN_HINT          104
#define IDS_SHORT_NAME_PLUGIN_DESCRIPTION 105
#define IDS_SHORT_NAME_PLUGIN_HINT      106
#define IDS_LONG_NAME_PLUGIN_DESCRIPTION 107
#define IDS_LONG_NAME_PLUGIN_HINT       108
#define IDS_SHORT_PATH_PLUGIN_DESCRIPTION 109
#define IDS_SHORT_PATH_PLUGIN_HINT      110
#define IDS_LONG_PATH_PLUGIN_DESCRIPTION 111
#define IDS_LONG_PATH_PLUGIN_HINT       112
#define IDS_LONG_UNC_PATH_PLUGIN_DESCRIPTION 113
#define IDS_LONG_UNC_PATH_PLUGIN_HINT   114
#define IDS_SHOW_ENTIRE_MENU_MENU_ITEM  115
#define IDS_SHOW_ENTIRE_MENU_HINT       116
#define IDS_SHOW_ENTIRE_MENU_WARNING    117
#define IDS_SHOW_ENTIRE_MENU_WARNING_TITLE 118
#define IDS_INTERNET_PATH_PLUGIN_DESCRIPTION 119
#define IDS_INTERNET_PATH_PLUGIN_HINT   120
#define IDS_UNIX_PATH_PLUGIN_DESCRIPTION 121
#define IDS_UNIX_PATH_PLUGIN_HINT       122
#define IDS_CYGWIN_PATH_PLUGIN_DESCRIPTION 123
#define IDS_CYGWIN_PATH_PLUGIN_HINT     124
#define IDS_DEFAULT_PLUGIN_DESCRIPTION  125
#define IDS_SHORT_UNC_PATH_PLUGIN_DESCRIPTION 126
#define IDS_SHORT_UNC_PATH_PLUGIN_HINT  127
#define IDS_LONG_FOLDER_PLUGIN_DESCRIPTION 128
#define IDS_LONG_FOLDER_PLUGIN_HINT     129
#define IDS_SHORT_FOLDER_PLUGIN_DESCRIPTION 130
#define IDS_SHORT_FOLDER_PLUGIN_HINT    131
#define IDS_SHORT_UNC_FOLDER_PLUGIN_DESCRIPTION 132
#define IDS_SHORT_UNC_FOLDER_PLUGIN_HINT 133
#define IDS_LONG_UNC_FOLDER_PLUGIN_DESCRIPTION 134
#define IDS_LONG_UNC_FOLDER_PLUGIN_HINT 135
#define IDS_PCC_SETTINGS_DESCRIPTION    136
#define IDS_PCC_SETTINGS_HINT           137
#define IDS_SETTINGS_APP_FILE_NAME      138
#define IDS_REDUNDANT_WORD_COPY         139
#define IDS_ANDROGYNOUS_NAME_PLUGIN_DESCRIPTION 140
#define IDS_ANDROGYNOUS_PATH_PLUGIN_DESCRIPTION 141
#define IDS_ANDROGYNOUS_UNC_PATH_PLUGIN_DESCRIPTION 142
#define IDS_ANDROGYNOUS_FOLDER_PLUGIN_DESCRIPTION 143
#define IDS_ANDROGYNOUS_UNC_FOLDER_PLUGIN_DESCRIPTION 144
#define IDR_PATHCOPYCOPYCONTEXTMENUEXT  201
#define IDR_PATHCOPYCOPYDATAHANDLER     202
#define IDR_PATHCOPYCOPYCONFIGHELPER    203
#define IDB_PCCICON2                    207

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        208
#define _APS_NEXT_COMMAND_VALUE         32768
#define _APS_NEXT_CONTROL_VALUE         201
#define _APS_NEXT_SYMED_VALUE           104
#endif
#endif
